apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-idp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: keycloak
    targetRevision: 21.6.0
    helm:
      parameters:
        - name: auth.adminUser
          value: admin
        - name: auth.adminPassword
          value: admin12345
        - name: production
          value: "false"
        - name: http.relativePath
          value: "/"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
